# Basic
title: 潘柏信
subtitle: 个人站
description: 
creator: <a href="http://www.baixin.io">@leopardpan</a>

url: "http://www.baixin.io"

permalink: /:year/:month/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: clear

# The blog button should not be removed.
blog_button:
    title: 博客

# Navigation buttons in the front page.s
nav:
    - {title: Wiki, description: Wiki, url: 'http://wiki.baixin.io'}     
    - {title: 标签, description: tags, url: '/tags'}      
    - {title: 所有文章, description: archive, url: '/archive'}   
    
# Pagination
gems: [jekyll-paginate,jekyll-sitemap]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    # disqus: leopard
    duoshuo: leopard 

# Social
social:
    weibo: 5366874726 
    github: leopardpan
    # twitter: 
    mail: leopardpan@icloud.com

# 百度统计
baidu:
    id: 8ba1c6be0953b6f9c2ba38e57f615421  

# Google Analytics
ga:
    id: UA-84134159-3   
    host: auto  
